### ISSUE TITLE
Multiple open trade offers - player can accept them all even if properties/cash has been traded already

### ISSUE THREAD

**Issue by Cujef** [rbuterbaugh/webopoly#2]
When a player has multiple trade offers sent/created, they are able to accept the offer from one person (complete transfer of properties and/or cash), and then accept another offer which may include previous properties already traded away. This allows for the player to manipulate the trade and get the benefits of all trades available, while screwing the other players out of their gained properties/cash.

**Comment by rbuterbaugh** [comment]
Fixed, please verify... I like to think people would be a bit more ethical! :)
