### ISSUE TITLE
Board / Play color changes - enchancement

### ISSUE THREAD

**Issue by Cujef** [rbuterbaugh/webopoly#3]
Attached is an image that suggests color changes that would be easier to view.
![webopoly_colors_compared](https://f.cloud.github.com/assets/5816729/2313017/af7f5360-a303-11e3-8fce-8781bf84d343.png)

**Comment by rbuterbaugh** [comment]
Fixed

**Comment by Cujef** [comment]
I assume we need to clear cookies and/or browser cache for the color changes to take effect?

**Comment by rbuterbaugh** [comment]
Yep, give it the good ol' Ctrl+F5

**Comment by Cujef** [comment]
Hmm cleared cache and did a ctrl+f5.. no dice. All we see are the new borders around property ownship. Weird

**Comment by rbuterbaugh** [comment]
Oh sorry about that, I totally didn't notice the changed colors for the player tokens. I'll start with the ones in the screenshot and play around with different options.

**Comment by rbuterbaugh** [comment]
Ok try another Ctrl+F5 and lemme know what you think

**Comment by Cujef** [comment]
Looks good!

**Comment by Cujef** [comment]
Sorry to loop back on this, but any chance of making the borders for property ownership black? Like the border in the screenshot?
![webop_suggest](https://f.cloud.github.com/assets/5816729/2322291/aefc021a-a3af-11e3-8102-338d5f163db4.png)

**Comment by rbuterbaugh** [comment]
Don't worry about it, happy to play around more. I didn't make it black originally because I felt like the quantity of black borders was too distracting. To balance it out, I've lightened the borders around board squares. I feel like it makes the board seem less harsh visually overall, but let me know what you think.
