### ISSUE TITLE
Card Draw - "Excess inventory selloff: pay $100"

### ISSUE THREAD

**Issue by Cujef** [rbuterbaugh/webopoly#6]
When a player lands on any of the 'draw a card' properties, one of the potential draws is a card that says, "Excess inventory selloff: pay $100"

If one were to sell off excess inventory, shouldn't they GAIN $100 instead of paying? :)

**Comment by rbuterbaugh** [comment]
Haha, it's supposed to be a loss of $100, so it's poorly worded, not incorrectly negated :)

I've updated the text to read "Excess inventory write-off: pay $100", which hopefully is more clear. Reopen if not
