### ISSUE TITLE
Card Draw - Player was caught filesharing and has to pay the fine

### ISSUE THREAD

**Issue by Cujef** [rbuterbaugh/webopoly#7]
When landing on one of the 'card draw' properties, a potential card that be drawn says something like, "Player was caught filesharing and has to pay the fine". However, it does not say how much the fine is for, so the play doesnt know what to account for if they have less than what the fine is. After you click ok to pay the fine, you find out the fine is $75.

Please add "($75)" to the main text regarding this card draw.

**Comment by rbuterbaugh** [comment]
I've looked through the cards but I'm not sure which card this refers to. I'll send you the list of all cards via email, let me know which one this is in reference to.

**Comment by Cujef** [comment]
![image](https://f.cloud.github.com/assets/5816729/2487568/9a9fdb04-b136-11e3-9738-911a49f8a16a.png)

**Comment by rbuterbaugh** [comment]
Fixed, give it the ole Ctrl+F5
